### ISSUE TITLE
Small screen: dark strip row with quote too tight

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/landscape.canonical.com#15]
As in large screen, the padding seems too small, mainly at the top.

I think the row with the partner logos also seems too tight at the top.

And the final row, with the CTA could also do with more top padding.

**Comment by richmccartney** [comment]
@yaili the dark strip row is exactly the same as any other I feel this is to do with the colour playing tricks on your eyes.

With the logo row this is because we have gone with the small caps and it removes line height unlike other rows with h1 / h2's at the top. Could we look at change the styles for that instead on mobile?

**Comment by yaili** [comment]
Yes, I understand. We'll have to review the spacing in rows across the board, I think it's too tight in small screen.

And the padding of the row shouldn't depend on the height of the headings inside it to keep consistent. I'll add issues to the vanilla theme project.

The CTA row needs equal padding top and bottom though. It's not the same in small screen.
